#!/bin/sh

STATUS=0

## Run linting
for LINTER in "pydocstyle" "pycodestyle" "mypy"
do 
  echo Running $LINTER
  if $LINTER astronomical
  then
    echo -e " -> \e[32mpassed\e[0m"
  else
    echo -e " -> \e[31mfailed\e[0m"
    STATUS=1
  fi
done

## Run tests
echo Running tests
if poetry run python3 -m pytest tests/. >/dev/null 2>&1
then
  echo -e " -> \e[32mpassed\e[0m"
else
  echo -e " -> \e[31mfailed\e[0m"
  STATUS=1
fi

exit $STATUS
